source 'https://gitlab.linphone.org/BC/public/podspec.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.3'

target 'iOSVoIPLib_Example' do
  pod 'iOSVoIPLib', :path => '../'
  pod 'QuickTableViewController'
  pod 'Swinject'
  
  target 'iOSVoIPLib_Tests' do
      inherit! :search_paths
  end
  
end

