source 'https://gitlab.linphone.org/BC/public/podspec.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.3'

target 'iOSPhoneLib_Example' do
  pod 'iOSPhoneLib', :path => '../'

  target 'iOSPhoneLib_Tests' do
    inherit! :search_paths

    
  end
end
